-- DEALING WITH TIMESTAMP AND NOW()

SELECT CURRENT_DATE();
SELECT CURRENT_TIME();
SELECT NOW(); -- {TO GET CURRENT DATE AND TIME} OR 
SELECT CURRENT_TIMESTAMP();

CREATE TABLE STUDENTS(
	ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    MOB INT(10),
    JOINING_DATE DATETIME
);

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS VALUES(1, 'Naik Sid', 86458970, NOW());

INSERT INTO STUDENTS VALUES
	(2, 'Naik Sanvi', 1234567, NOW()),
    (3, 'Naik Sam', 98765345, CURRENT_TIMESTAMP()
);