-- TRANSACTIONS - SQL IS BY-DEFUALT IN AUTOCOMMIT MODE

SELECT * FROM EMP;

SELECT @@AUTOCOMMIT;
SET AUTOCOMMIT = 0;

START TRANSACTION;
DELETE FROM EMP WHERE AGE < 18;
UPDATE EMP SET AGE = AGE + 1;
DELETE FROM EMP WHERE GENDER = 'F';

ROLLBACK;
COMMIT;

SET AUTOCOMMIT = 1;
DELETE FROM EMP WHERE ID = 32;
ROLLBACK; -- NOW IT'LL NOT WORK BECOZ IT IS IN AUTOCOMMMIT MODE