SELECT * FROM EMP;

UPDATE EMP SET AGE = 20 WHERE EMP_ID = 2;

UPDATE EMP SET AGE = AGE + 1;

UPDATE EMP SET NAME = "Naik Sid", AGE = 20 WHERE EMP_ID = 2;

ALTER TABLE EMP ADD COLUMN GRADE VARCHAR(3) DEFAULT '12';
UPDATE EMP SET GRADE = '10' WHERE AGE < 16;